backend:
  name: git-gateway
  branch: main
media_folder: "/assets/uploads"
site_url: https://theunitedgenerations.com
display_url: https://theunitedgenerations.com
collections:
  - name: "news"
    label: "News"
    label_singular: "News Item"
    editor: { preview: false }
    folder: "news/"
    create: true
    preview_path: "/news/{{slug}}"
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - name: "title"
        label: "Title"
        widget: string
      - name: "date"
        label: "Publish date"
        widget: "date"
      - name: "featured_image"
        label: "Featured Image"
        widget: "object"
        required: false
        fields:
          - name: image
            required: false
            label: Image
            widget: image
          - name: alt
            required: false
            label: Description
            widget: string
            hint: "You can add a description, sometimes called alt-text, to your photos so they’re accessible to more people, including those who are blind or visually impaired."
      - name: "introduction"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
      - name: "body"
        label: Content
        widget: markdown
  - name: "events"
    label: "Events"
    preview_path: "/events/"
    label_singular: "Event"
    editor: { preview: false }
    folder: "events/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: "eyebrow"
        label: "Eyebrow"
        required: false
        widget: string
        hint: Appears above the title and is used for filtering
      - name: "date"
        label: "Event date"
        widget: "date"
      - name: "time"
        label: "Event Time"
        widget: "string"
        required: false
      - name: "location"
        label: "Event location"
        widget: "string"
      - name: "featured_image"
        label: "Featured Image"
        widget: "object"
        fields:
          - name: image
            label: Image
            widget: image
          - name: alt
            label: Alt text
            widget: string
            hint: "You can add a description, sometimes called alt-text, to your photos so they’re accessible to more people, including those who are blind or visually impaired."
      - name: "introduction"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
      - name: "link"
        label: Link
        widget: object
        required: false
        fields:
          - name: url
            label: URL
            widget: string
            required: false
          - name: text
            label: Link Text
            widget: string
            required: false
  - name: "research"
    label: "Research"
    label_singular: "Research Chapter"
    preview_path: "/research/{{slug}}"
    editor: { preview: false }
    folder: "research/"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["commit_date", "title", "date"]
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "chapter"
      - name: "title"
        label: "Title"
        widget: string
      - name: "date"
        label: "Publication Date"
        widget: "datetime"
      - widget: "number"
        label: "Order"
        name: "order"
        hint: "This is used to determine in which order the chapters appear."
      - name: introduction
        label: Introduction
        widget: text
        required: false
      - name: body
        label: "Copy"
        widget: "markdown"
  - name: "books"
    label: "Books"
    preview_path: "/books/"
    label_singular: "Book"
    editor: { preview: false }
    folder: "books/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: "date"
        label: "Publication Date"
        widget: "date"
      - name: "featured_image"
        label: "Featured Image"
        widget: "object"
        fields:
          - name: image
            label: Image
            widget: image
            media_library:
              config:
                max_file_size: 6000000
          - name: alt
            label: Description
            widget: string
            hint: "You can add a description, sometimes called alt-text, to your photos so they’re accessible to more people, including those who are blind or visually impaired."
      - name: "intro"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
      - name: "link"
        label: Link
        widget: object
        fields:
          - name: url
            label: URL
            widget: string
          - name: text
            label: Link Text
            widget: string
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    preview_path: "{{title | slug}}"
    editor: { preview: false }
    folder: "pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: "intro"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
      - name: "body"
        label: Content
        widget: markdown
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - file: "_data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
          - label: "Site Description"
            name: "site_description"
            widget: "string"
            hint: "This is displayed in the header, search results and social media cards."
          - label: Show Content
            name: show_content
            widget: boolean
          - label: Footer Menu
            label_singular: Menu Item
            name: footer_menu
            widget: list
            fields:
              - label: URL
                name: url
                widget: string
              - label: Link Text
                name: title
                widget: string
              - label: Open in a new Tab?
                name: target
                widget: boolean
                required: false

      - file: "_data/about.json"
        name: "about"
        label: "Information"
        fields:
          - label: "Introduction"
            name: "intro"
            widget: "markdown"
            editor_components: []
          - label: "Copy"
            name: "content"
            widget: "markdown"
      - file: "_data/research.json"
        name: "research"
        label: "Research"
        fields:
          - label: "Introduction"
            name: "intro"
            widget: "markdown"
            editor_components: []
          - label: "Hero Image"
            name: "hero"
            widget: "object"
            fields:
              - name: src
                label: Image
                widget: image
                media_library:
                  config:
                    max_file_size: 6000000
              - name: alt
                label: Alt
                widget: string
      - file: "_data/books.json"
        name: "books"
        label: "Books"
        fields:
          - label: "Introduction"
            name: "intro"
            widget: "markdown"
            editor_components: []
      - file: "_data/events.json"
        name: "events"
        label: "Events"
        fields:
          - label: "Introduction"
            name: "intro"
            widget: "markdown"
            editor_components: []
      - file: "_data/news.json"
        name: "news"
        label: "News"
        fields:
          - label: "Introduction"
            name: "intro"
            widget: "markdown"
            editor_components: []
      - file: "_data/home.json"
        name: "home"
        label: "Home"
        fields:
          - label: "Copy"
            name: "content"
            widget: "markdown"
            buttons: [bold, italic, link, heading-two, bulleted-list]
          - label: "Hero Images"
            name: "hero_images"
            widget: "list"
            summary: "{{fields.url}}"
            fields:
              - label: Image
                name: url
                widget: "image"
              - label: "Description"
                name: "alt"
                widget: "text"
                hint: "You can add a description to your images so they’re accessible to more people, including those who are blind or visually impaired. Good descriptions are concise, but present what’s in your photos accurately enough to understand their context."
