backend:
  name: git-gateway
  branch: main
media_folder: "/assets/uploads"
collections:
  - name: "news"
    label: "News"
    label_singular: "News Item"
    editor: { preview: false }
    folder: "news/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: "date"
        label: "Publish date"
        widget: "date"
      - name: "featured_image"
        label: "Featured Image"
        widget: "object"
        fields:
          - name: image
            label: Image
            widget: image
          - name: alt
            label: Description
            widget: string
            hint: "You can add a description, sometimes called alt-text, to your photos so they’re accessible to more people, including those who are blind or visually impaired."
      - name: "introduction"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
  - name: "events"
    label: "Events"
    label_singular: "Event"
    editor: { preview: false }
    folder: "events/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: "eyebrow"
        label: "Eyebrow"
        required: false
        widget: string
        hint: Appears above the title and is used for filtering
      - name: "date"
        label: "Event date"
        widget: "date"
      - name: "location"
        label: "Event location"
        widget: "string"
      - name: "featured_image"
        label: "Featured Image"
        widget: "object"
        fields:
          - name: image
            label: Image
            widget: image
          - name: alt
            label: Description
            widget: string
            hint: "You can add a description, sometimes called alt-text, to your photos so they’re accessible to more people, including those who are blind or visually impaired."
      - name: "introduction"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
      - name: "link"
        label: Link
        widget: object
        fields:
          - name: url
            label: URL
            widget: string
          - name: text
            label: Link Text
            widget: string
  - name: "research"
    label: "Research"
    label_singular: "Research Chapter"
    editor: { preview: false }
    folder: "research/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: content
        label: "Copy"
        widget: "markdown"
  - name: "books"
    label: "Books"
    label_singular: "Book"
    editor: { preview: false }
    folder: "books/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: string
      - name: "featured_image"
        label: "Featured Image"
        widget: "object"
      - name: "date"
        label: "Publication Date"
        widget: "date"
        fields:
          - name: image
            label: Image
            widget: image
            media_library:
              config:
                max_file_size: 6000000
          - name: alt
            label: Description
            widget: string
            hint: "You can add a description, sometimes called alt-text, to your photos so they’re accessible to more people, including those who are blind or visually impaired."
      - name: "intro"
        label: "Introduction"
        widget: "markdown"
        editor_components: []
        buttons:
          - bold
          - italic
      - name: "link"
        label: Link
        widget: object
        fields:
          - name: url
            label: URL
            widget: string
          - name: text
            label: Link Text
            widget: string
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - file: "_data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
          - label: "Site Description"
            name: "site_description"
            widget: "string"
            hint: "This is displayed in the header, search results and social media cards."
          - label: Show Content
            name: show_content
            widget: boolean
      - file: "_data/about.json"
        name: "about"
        label: "About"
        fields:
          - label: "Copy"
            name: "content"
            widget: "markdown"
      - file: "_data/home.json"
        name: "home"
        label: "Home"
        fields:
          - label: "Copy"
            name: "content"
            widget: "markdown"
            buttons: [bold, italic, link, heading-two, bulleted-list]
          - label: "Hero Images"
            name: "hero_images"
            widget: "list"
            summary: "{{fields.url}}"
            fields:
              - label: Image
                name: url
                widget: "image"
              - label: "Description"
                name: "alt"
                widget: "text"
                hint: "You can add a description to your images so they’re accessible to more people, including those who are blind or visually impaired. Good descriptions are concise, but present what’s in your photos accurately enough to understand their context."
